# Generated by Django 3.1 on 2020-10-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_product_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
